=== camenduru/consisid-tost/schema.json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "type": "object",
  "properties": {
    "readme": {
      "type": "string",
      "title": "Identity-Preserving Text-to-Video Generation by Frequency Decomposition",
      "author": "Shenghai Yuan, Jinfa Huang, Xianyi He, Yunyuan Ge, Yujun Shi, Liuhan Chen, Jiebo Luo, Li Yuan",
      "page": "https://pku-yuangroup.github.io/ConsisID/",
      "code": "https://github.com/PKU-YuanGroup/ConsisID",
      "paper": "https://arxiv.org/abs/2411.17440",
      "jupyter": "https://github.com/camenduru/ConsisID-jupyter",
      "api": "https://github.com/camenduru/tost-api-examples/blob/main/v1/consisid.ipynb",
      "tags": [
        "Image to Video"
      ],
      "widget": "readme"
    },
    "upload": {
      "type": "string",
      "widget": "upload",
      "upload_url": "https://litterbox.catbox.moe/resources/internals/api.php",
      "property": "input_image"
    },
    "input_image": {
      "type": "string",
      "description": "Image URL",
      "widget": "textarea"
    },
    "prompt": {
      "type": "string",
      "description": "Prompt",
      "widget": "textarea"
    },
    "num_inference_steps": {
      "type": "integer",
      "description": "Num Inference Steps"
    },
    "guidance_scale": {
      "type": "number",
      "description": "Guidance scale"
    },
    "seed": {
      "type": "integer",
      "description": "Seed"
    },
    "example": {
      "type": "string",
      "image1": "https://fakeimg.pl/512x512/282828/eae0d0/?text=input#.png",
      "image2": "https://files.catbox.moe/wy4gq7.jpg",
      "image3": "https://fakeimg.pl/512x512/282828/eae0d0/?text=output#.png",
      "image4": "https://files.catbox.moe/ri8l7s.mp4",
      "video_aspect_ratio": "70%",
      "widget": "example"
    }
  },
  "buttons": [
    {
      "id": "enter",
      "label": "ðŸ¥ª Enter"
    }
  ]
}

=== camenduru/consisid-tost/model.json
{
    "input_image": "https://files.catbox.moe/wy4gq7.jpg",
    "prompt": "A woman adorned with a delicate flower crown, is standing amidst a field of gently swaying wildflowers. Her eyes sparkle with a serene gaze, and a faint smile graces her lips, suggesting a moment of peaceful contentment. The shot is framed from the waist up, highlighting the gentle breeze lightly tousling her hair. The background reveals an expansive meadow under a bright blue sky, capturing the tranquility of a sunny afternoon.",
    "num_inference_steps": 50,
    "guidance_scale": 7.0,
    "seed": 0
}
